# Generated by Django 5.2.17 on 2026-08-24 13:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_id', models.IntegerField(unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('console_id', models.IntegerField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('released_date', models.CharField(blank=True, max_length=50, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('developer', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('cover_url', models.URLField(blank=True, max_length=500, null=True)),
                ('title_screen_url', models.URLField(blank=True, max_length=500, null=True)),
                ('ingame_screen_url', models.URLField(blank=True, max_length=500, null=True)),
                ('total_players', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RomHack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('translation', 'Tradução'), ('improvement', 'Melhoria / Quality of Life'), ('complete_hack', 'Overhaul / Jogo Novo'), ('difficulty', 'Balanceamento / Dificuldade')], default='translation', max_length=20)),
                ('description', models.TextField()),
                ('patch_url', models.URLField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_hacks', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hacks', to='core.game')),
            ],
        ),
        migrations.CreateModel(
            name='HackRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hack_ratings', to=settings.AUTH_USER_MODEL)),
                ('hack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.romhack')),
            ],
            options={
                'unique_together': {('hack', 'user')},
            },
        ),
    ]
